"""GUI STRINGS (zh / en) — photo_s.gui.strings (v2.0).

Moved verbatim from the former photo_s/gui.py. zh/en key sets must stay
identical (tests/test_gui_settings.py enforces parity — _t silently
falls back on a missing key, so drift reads as "works" but untranslated).
DEFAULT_LANG ("zh") is the fallback language for missing-key lookups.
"""

# Fallback for _t missing-key lookups — NOT the startup default anymore.
# Startup language comes from i18n.resolve_language() (persisted > env > system).
DEFAULT_LANG = "zh"


STRINGS = {
    "zh": {
        "window_title": "PhotoS — 图片批量压缩与格式转换",
        "subtitle": "批量图片压缩与格式转换工具",
        "about": "关于",
        "theme_toggle": "切换深色/浅色模式",
        # Toolbar / file list
        "add_images": "添加图片",
        "add_folder": "添加文件夹",
        "remove": "移除",
        "clear": "清除全部",
        "files_count": "{n} 个文件",
        "files_count_checked": "{n} 个文件 · 已勾选 {m} 个",
        "check_none": "请先勾选要处理的图片（勾选框切换，用「全选/全不选」按钮批量切换）",
        "check_toggle_all": "全选/全不选",
        "undo": "撤销",
        "undo_none": "没有可撤销的操作",
        "undo_failed": "撤销失败: {err}",
        "redo": "重做",
        "redo_none": "没有可重做的操作",
        "undo_removed": "撤销移除 {n} 张",
        "undo_dedup": "撤销去重移动 {n} 张",
        "undo_tag": "撤销打标: {name}",
        "undo_done": "已撤销",
        "about_shortcuts": "快捷键 Shortcuts",
        "shortcuts_text": "⌘O / Ctrl+O 添加图片\n⌘⇧O / Ctrl+Shift+O 添加文件夹\n⌘R / Ctrl+R 开始处理（Esc 取消）\n⌘P / Ctrl+P 预览参数\n⌘E / Ctrl+E 审查打分\n⌘D / Ctrl+D 去重查看\n⌘G / Ctrl+G 导出画廊\n⌘Z / Ctrl+Z 撤销\n（审查窗口内：←/→ 翻页，0-5 评分，⌘Z 撤销，Esc 关闭）",
        "dlg_skipped": "已导入 {n} 张图片，跳过 {m} 个不支持的文件",
        "dlg_no_supported": "未找到支持的图片（跳过 {m} 个不支持的文件）",
        "hint_dnd": "将图片或文件夹拖入列表，或使用上方按钮添加",
        "hint_no_dnd": "使用上方按钮添加图片文件（安装 tkinterdnd2 可启用拖放）",
        "col_name": "文件名",
        "col_size": "大小",
        "col_format": "格式",
        "col_dims": "尺寸",
        # Settings sections
        "sec_format": "输出格式",
        "sec_mode": "压缩模式",
        "manual_quality": "手动质量",
        "target_size_mode": "目标大小",
        "quality": "质量",
        "max_quality": "最高质量上限",
        "target_size": "目标大小",
        "autotune_hint": "自动调整质量",
        "sec_resize": "缩放",
        "width": "宽",
        "height": "高",
        "pixels_hint": "像素，留空 = 不缩放",
        "scale": "缩放比例 %",
        "sec_output": "输出位置",
        "browse": "浏览…",
        "sec_naming": "文件命名",
        "prefix": "前缀",
        "suffix": "后缀",
        "smart_rename": "智能重命名",
        "rename_vars": "变量: {date} {camera} {original} {seq} {iso} {focal}",
        "sec_subfolder": "子文件夹",
        "template": "模板",
        "preset_flat": "不分类",
        "preset_date": "按日期",
        "preset_camera": "按相机",
        "preset_date_camera": "按日期+相机",
        "preset_custom": "自定义…",
        "custom": "自定义",
        "folder_vars": "留空 = 不分类。变量: {year} {month} {day} {date} {camera} {make}",
        "sec_options": "选项",
        "preserve_exif": "保留 EXIF 信息",
        "optimize": "优化压缩",
        "progressive": "渐进式 JPEG",
        "jpeg_subsampling": "JPEG 色度子采样（444 全色彩）",
        "overwrite": "覆盖已存在文件",
        "auto_rotate": "按 EXIF 方向自动旋转",
        "raw_half_size": "RAW 半尺寸解码（更快）",
        "raw_auto_bright": "RAW 自动亮度",
        "raw_demosaic": "RAW 去马赛克算法",
        "raw_color_space": "RAW 色彩空间",
        "raw_16bit": "RAW 16-bit 解码（TIFF 输出）",
        "delete_original": "处理后删除原文件",
        "strip_gps": "移除 GPS 位置信息",
        "keep_mtime": "保留修改时间",
        "max_pixels": "最长边像素上限",
        "max_pixels_hint": "像素，留空 = 不限制，仅缩小",
        "jobs": "并行线程",
        # Cutout / background removal (v2.1.0)
        "sec_cutout": "抠图（背景移除）",
        "cutout_mode": "模式",
        "cutout_off": "关闭",
        "cutout_subject": "主体（AI）",
        "cutout_person": "人物（AI）",
        "cutout_object": "物体（AI）",
        "cutout_color": "颜色键控",
        "cutout_label": "COCO 类别",
        "cutout_r": "R",
        "cutout_g": "G",
        "cutout_b": "B",
        "cutout_tol": "容差",
        "cutout_feather": "羽化",
        "cutout_hint": "透明背景需 PNG/WebP/TIFF/AVIF/HEIC；JPEG 按文件报错",
        "cutout_ai_hint": "AI 分割需 photo-s-tools[enhance]；首次使用自动下载权重",
        # Bottom bar
        "ready": "就绪 — 添加图片文件开始处理",
        "preview": "预览",
        "start": "开始处理",
        "cancel": "取消",
        "cancelling": "正在取消…",
        "processing": "正在处理…",
        "processing_item": "正在处理 [{cur}/{total}] {name}",
        "tuning": "调整质量中…",
        "cancelled_status": "已取消 — {ok} 个完成，{fail} 个失败/未处理",
        "done_status": "完成 — {ok}/{total} 成功，节省 {savings} ({pct}%)",
        "failed_status": "处理失败",
        "stats_result": "原始: {sin} → 压缩后: {sout}  |  节省 {pct}%",
        "stats_files": "已选择 {n} 个文件  |  总大小: {size}",
        "stats_files_only": "已选择 {n} 个文件",
        # Dialogs
        "dlg_no_files_title": "无文件",
        "dlg_no_files": "请先添加图片文件。",
        "dlg_confirm_clear_title": "确认清除",
        "dlg_confirm_clear": "确定要清除所有 {n} 个文件吗？",
        "dlg_added_title": "已添加",
        "dlg_added": "文件夹中的 {n} 个图片已在列表中。",
        "dlg_no_images_title": "未找到图片",
        "dlg_no_images": "该文件夹中没有支持的图片文件。",
        "dlg_drop_none": "拖入的内容中没有可添加的图片文件。",
        "dlg_confirm_delete_title": "确认删除",
        "dlg_confirm_delete": "处理完成后将删除 {n} 个原始文件！\n\n确定继续？",
        "dlg_error_title": "处理错误",
        "dlg_error": "批处理过程中发生错误:\n\n{err}",
        # Preview
        "preview_title": "预览",
        "preview_header": "预览 — 不会实际处理文件",
        "pv_files": "文件数量: {n}",
        "pv_format": "目标格式: {fmt}",
        "pv_target": "目标大小: {size}（自动调优）",
        "pv_qmax": "质量上限: {q}",
        "pv_quality": "质量: {q}",
        "pv_maxsize": "最大尺寸: {w}×{h}",
        "pv_scale": "缩放比例: {s}%",
        "pv_exif": "保留 EXIF: {yn}",
        "pv_optimize": "优化: {yn}",
        "pv_progressive": "渐进式: {yn}",
        "pv_overwrite": "覆盖: {yn}",
        "pv_outdir": "输出目录: {d}",
        "pv_outdir_same": "（与源文件相同）",
        "pv_subfolder": "子文件夹: {p}",
        "pv_prefix": "前缀: '{p}'",
        "pv_suffix": "后缀: '{s}'",
        "pv_total": "源文件总大小: {size}",
        "yes": "是",
        "no": "否",
        "auto": "自动",
        # Summary / comparison
        "summary_title": "处理完成",
        "sum_header": "处理完成",
        "sum_success": "成功",
        "sum_failed": "失败",
        "sum_original": "原始大小",
        "sum_compressed": "压缩后",
        "sum_saved": "节省",
        "sum_ask_compare": "显示压缩对比？",
        "sum_view_compare": "查看前后对比",
        "compare_title": "压缩对比",
        "compare_header": "压缩前后对比",
        "before": "原始",
        "after": "压缩后",
        "saved": "节省",
        "quality_lbl": "质量",
        "cannot_load": "无法加载",
        "close": "关闭",
        # Plugins
        "plugins": "插件",
        "plugins_title": "插件管理",
        "plugins_installed": "已安装插件",
        "plugins_available": "官方可用插件",
        "plugins_none": "（无）",
        "plugins_install": "安装",
        "plugins_uninstall": "卸载",
        "plugins_fetch": "预下载权重",
        "plugins_refresh": "刷新",
        "plugins_ok": "✅ {what}",
        "plugins_err": "❌ {detail}",
        # Exposure analysis
        "analyze": "曝光分析",
        "review_btn": "审查打分",
        "dedup_btn": "去重",
        "gallery_btn": "画廊",
        "gallery_title": "导出画廊",
        "gallery_name": "画廊标题",
        "gallery_thumb": "缩略图尺寸",
        "gallery_out": "输出目录",
        "gallery_generate": "生成画廊",
        "gallery_generating": "生成中…",
        "gallery_done": "已生成 {count} 张 → {path}",
        "gallery_open": "在浏览器打开",
        "gallery_need_files": "请先添加图片",
        "gallery_need_dir": "请选择输出目录",
        "gallery_error": "生成失败: {err}",
        "op_failed": "操作失败: {err}",
        "dedup_title": "去重查看",
        "dedup_scanning": "扫描中… {n}/{total}",
        "dedup_none": "未发现重复图片",
        "dedup_group": "第 {i} 组",
        "dedup_keep": "保留",
        "dedup_sharpest": "★最锐",
        "dedup_blur": "锐度",
        "dedup_execute": "移入回收子文件夹",
        "dedup_moving": "移动中…",
        "dedup_moved": "已移动 {n} 张到 {dir}",
        "dedup_rescan": "重新扫描",
        "dedup_confirm": "将 {n} 张图片移动到回收子文件夹（不会删除），继续？",
        "dedup_none_selected": "没有要清理的图片（每组至少保留一张）",
        "review_title": "审查打分",
        "review_pos": "{i} / {n}",
        "review_loading": "读取元数据… {n}/{total}",
        "review_rating": "评分",
        "review_keywords": "关键词",
        "review_title_lbl": "标题",
        "review_save": "保存",
        "review_saved": "已保存",
        "review_save_failed": "写入失败: {err}",
        "review_filter": "过滤",
        "review_min_rating": "最低评分",
        "review_filter_kw": "关键词包含",
        "review_apply_filter": "应用过滤",
        "review_clear_filter": "清除过滤",
        "review_empty": "没有匹配的图片",
        "review_no_piexif": "⚠️ 未安装 piexif：只能查看，无法写入（pip install photo-s-tools[exif]）",
        "review_prev": "◀ 上一张",
        "review_next": "下一张 ▶",
        "review_none": "请先添加图片",
        "review_shooting": "拍摄信息",
        "review_make": "品牌",
        "review_model": "型号",
        "review_lens": "镜头",
        "review_iso": "ISO",
        "review_shutter": "快门(如 1/250)",
        "review_aperture": "光圈(如 2.8)",
        "review_date": "日期(YYYY:MM:DD HH:MM:SS)",
        "review_select_lbl": "精选",
        "review_rejects_lbl": "淘汰",
        "review_select_go": "移动精选/淘汰",
        "review_select_browse": "选择目标文件夹",
        "review_select_need_dir": "请至少指定一个目标文件夹（精选或淘汰）",
        "review_select_done": "已移动 {n} 个文件",
        "review_select_done_warn": "移动 {ok} 个，{err} 个失败",
        "analyze_title": "曝光统计",
        "analyze_none": "请先在文件列表中选择一张图片",
        "analyze_err": "无法读取该图片",
        "analyze_luminance": "平均亮度",
        "analyze_over": "过曝 (≥250)",
        "analyze_under": "欠曝 (≤5)",
        "analyze_blur": "模糊分",
        "analyze_histogram": "亮度直方图",
        # Settings dialog (MCP + optional deps)
        "settings": "设置",
        "settings_title": "设置",
        "set_mcp": "MCP 服务器",
        "set_mcp_desc": "让 Claude Desktop 等 MCP 客户端直接调用 PhotoS 工具",
        "mcp_installed": "已安装",
        "mcp_missing": "未安装",
        "mcp_install_hint": "安装 Install: pip install 'photo-s-tools[mcp]'",
        "mcp_launch": "启动命令 Launch command",
        "mcp_claude_config": "Claude Desktop 配置 Claude Desktop config",
        "mcp_claude_snippet": (
            "{\n  \"mcpServers\": {\n    \"photo-s\": {\n"
            "      \"command\": \"photo-s\",\n      \"args\": [\"mcp\"]\n"
            "    }\n  }\n}"
        ),
        "copy": "复制",
        "copied": "已复制",
        "set_deps": "可选依赖 Optional dependencies",
        "dep_install": "安装",
        "dep_installing": "安装中…",
        "set_plugins_link": "打开插件管理器 Open Plugin Manager",
        # Watermark
        "sec_watermark": "水印",
        "wm_text": "文字",
        "wm_image": "图片",
        "wm_position": "位置",
        "wm_opacity": "透明度",
        # Multi-size
        "sec_sizes": "多尺寸输出",
        "sizes_hint": "格式 format: 标签:宽x高, e.g. thumb:480x,screen:1920x1080",
        # Adjust
        "sec_adjust": "影调调整",
        "brightness": "亮度",
        "contrast": "对比度",
        "saturation": "饱和度",
        "gamma": "伽马",
        "sharpen": "锐化",
        "export_sharpen": "导出锐化（0 关闭）",
        "highlight_recovery": "高光恢复（0 关闭）",
        "grayscale": "黑白",
        "sepia": "复古",
        # Composition
        "sec_composition": "构图",
        "crop": "裁剪",
        "crop_hint": "格式 format: 宽x高+偏移 800x600+100+50",
        "crop_ratio": "比例裁剪",
        "rotate": "旋转°",
        "rotate_bg": "旋转底色",
        "flip": "翻转",
        "flip_hint": "h = 水平, v = 垂直",
        "pad": "留白比例",
        "pad_bg": "留白底色",
        "pad_hint": "e.g. 16:9, 1:1（空 = 不补边）",
        # Correction (exposure / LOG / denoise / straighten)
        "sec_correction": "校正",
        "ev": "曝光补偿 (EV)",
        "ev_hint": "EV 档位，2^EV 增益（0 = 不变）",
        "auto_exposure": "自动曝光目标 (0-1)",
        "auto_exposure_hint": "均值亮度归一化（空 = 关闭）",
        "log_curve": "LOG 还原",
        "log_curve_hint": "SLOG3/CLOG3/LOGC3/DLOG/VLOG/HLG（空 = 关闭）",
        "denoise": "降噪强度 (0-20)",
        "denoise_hint": "NLM 降噪（空 = 关闭；需 photo-s-tools[enhance] 或 SCUNet 插件）",
        "lut": "LUT 调色 (.cube)",
        "lut_hint": ".cube 文件或预设名（装 photo-s-plugin-lut 后可用 "
                    "filmic-v1 等；空 = 关闭）",
        "auto_straighten": "自动扶正地平线",
        "max_straighten_angle": "最大扶正角°",
        # White balance / color / evaluation
        "wb_temp": "白平衡色温 (K)",
        "wb_temp_hint": "如 5600；空 = 不调整",
        "wb_reference": "白平衡参考图",
        "wb_reference_hint": "灰卡图路径；空 = 不采样",
        "browse_ref": "浏览…",
        # Lightroom-direction grading (v1.6.0)
        "sec_grading": "调色（LR 方向）",
        "wb_tint": "白平衡 tint (绿-/品红+)",
        "wb_tint_hint": "-100~100；空 = 关闭",
        "levels": "手动色阶",
        "levels_hint": "黑,白[,伽马] 如 80,200,1.1；空 = 关闭",
        "curves": "点曲线",
        "curves_hint": "每通道控制点 ch:x,y;x,y 如 0,0;128,140;255,255；空 = 关闭",
        "vibrance": "自然饱和度",
        "vibrance_hint": "-1~1；空 = 关闭",
        "color_grading": "三向颜色分级",
        "color_grading_hint": "zone:hue,sat 如 shadows:120,0.3；空 = 关闭",
        "hsl": "HSL 分色",
        "hsl_hint": "color:h,s,l 如 green:10,0.2,0.1；空 = 关闭",
        "clarity": "清晰度",
        "clarity_hint": "-1~1；空 = 关闭",
        "texture": "纹理",
        "texture_hint": "-1~1；空 = 关闭",
        "dehaze": "去雾",
        "dehaze_hint": "-1~1（负 = 加雾）；空 = 关闭",
        "vignette": "暗角",
        "vignette_hint": "amount[,mid[,feather]]；空 = 关闭",
        "grain": "颗粒",
        "grain_hint": "amount[,size]；空 = 关闭",
        # Local adjustments + lens correction (v1.7.0)
        "point_color": "点颜色",
        "point_color_hint": "取样色定向调整 r,g,b:h,s,l[,range]；空 = 关闭",
        "edit_point_color": "点颜色…",
        "masks": "局部蒙版",
        "masks_hint": "线性/径向/颜色范围蒙版 + 蒙版内局部调整；空 = 关闭",
        "edit_masks": "蒙版…",
        "sec_lens": "镜头矫正",
        "lens_distort": "畸变 k1",
        "lens_distort_hint": "正 = 矫正桶形，负 = 枕形；空 = 关闭",
        "lens_vignette": "去暗角",
        "lens_vignette_hint": "amount[,midpoint]；空 = 关闭",
        "lens_ca": "消色差",
        "lens_ca_hint": "r_scale,b_scale 如 0.999,1.001；空 = 关闭",
        "lens_profile": "镜头档案（lens-profile save 维护）",
        "dlt_point_color": "点颜色（取样色 + 范围）",
        "dlt_masks": "局部蒙版编辑器",
        "pc_add": "添加",
        "pc_update": "更新",
        "pc_delete": "删除",
        "pc_sample": "取样色 (R,G,B)",
        "pc_hue": "色相偏移",
        "pc_sat": "饱和度",
        "pc_lum": "明度",
        "pc_range": "范围容差",
        "mask_name": "名称",
        "mask_type": "类型",
        "mask_linear": "线性渐变",
        "mask_radial": "径向椭圆",
        "mask_color": "颜色范围",
        "mask_brush": "笔刷",
        "mask_brush_size": "笔刷半径（相对短边）",
        "mask_brush_clear": "清空笔迹",
        "mask_workflow": "画布蒙版（LR 式）",
        "mask_prev": "◀ 上一张",
        "mask_next": "下一张 ▶",
        "mask_page": "第 {cur}/{total} 张",
        "mask_add": "新建蒙版",
        "mask_list": "蒙版列表",
        "mask_show": "显示",
        "mask_hide": "隐藏",
        "mask_del": "删除蒙版",
        "mask_undo": "撤销 (⌘Z)",
        "mask_mode_add": "A 添加",
        "mask_mode_subtract": "B 减去",
        "mask_mode_off": "◦ 新建",
        "mask_up": "▲ 上移",
        "mask_down": "▼ 下移",
        "mask_drag_hint": "空白处拖动 = 绘制；拖拽蒙版内部 = 移动位置",
        "mask_ai_empty": "AI 未识别到该内容（蒙版为空）",
        "mask_ai_overlay_warn":
            "AI 蒙版无法渲染（缺 opencv 或权重未下载）：列表中的 AI "
            "蒙版不会显示在画布上，批量处理时该照片会失败。"
            "可先安装 photo-s-tools[enhance] 或运行 photo-s info 检查。",
        "mask_bad_segment_warn":
            "蒙版字符串含无法解析的段，已跳过损坏段、保留其余蒙版。"
            "（原先会把整串蒙版全部清空）",
        "preview_per_photo_hint":
            "注：预览不含逐照片蒙版（批量处理时才注入）",
        "mask_tool": "蒙版工具",
        "mask_tool_linear": "线性渐变",
        "mask_tool_radial": "径向椭圆",
        "mask_tool_brush": "笔刷",
        "mask_tool_color": "颜色取样",
        "mask_tool_subject": "AI 主体",
        "mask_tool_person": "AI 人物",
        "mask_tool_object": "AI 对象",
        "mask_ai_label": "对象类别（COCO）",
        "mask_overlay_hint": "画布上拖动绘制蒙版；红色/彩色半透明区域 = 蒙版生效区（叠加显示所有可见蒙版）",
        "mask_apply_all": "应用到全部勾选照片",
        "mask_empty_hint": "勾选文件后在画布上绘制蒙版",
        "mask_no_check": "请先勾选要编辑的照片",
        "mask_feather": "羽化",
        "mask_invert": "反相",
        "mask_params": "参数",
        "mask_adjust_sec": "蒙版内调整（滑杆，0 = 不动）",
        "adj_exposure": "曝光 EV",
        "adj_brightness": "亮度",
        "adj_contrast": "对比度",
        "adj_saturation": "饱和度",
        "adj_vibrance": "自然饱和度",
        "adj_clarity": "清晰度",
        "adj_texture": "纹理",
        "adj_sharpen": "锐化",
        "adj_temp": "色温 K",
        "adj_tint": "tint 绿-/品红+",
        "adj_blur": "模糊半径 px",
        "mask_preview": "蒙版预览",
        "mask_refresh": "刷新预览",
        "mask_no_preview": "勾选文件后可预览",
        # settings category tabs (v1.6.1)
        "tab_output": "输出",
        "tab_adjust": "调整",
        "tab_fx": "效果",
        "tab_metadata": "元数据",
        "tab_options": "选项",
        # interactive editors (v1.6.x)
        "edit_curves": "编辑曲线…",
        "edit_wheels": "色轮…",
        "edit_hsl": "HSL…",
        "dlt_curves": "曲线编辑器（拖拽控制点，双击加点，右键删点）",
        "dlt_wheels": "颜色分级（点击/拖拽选色）",
        "dlt_hsl": "HSL 分色（点色块，再拖滑块）",
        "ok": "确定",
        "grade_none": "未设置",
        "grade_lum": "亮度",
        "reset": "复位",
        "zone_shadows": "阴影",
        "zone_midtones": "中间调",
        "zone_highlights": "高光",
        "hsl_red": "红色",
        "hsl_orange": "橙色",
        "hsl_yellow": "黄色",
        "hsl_green": "绿色",
        "hsl_aqua": "青色",
        "hsl_blue": "蓝色",
        "hsl_purple": "紫色",
        "hsl_magenta": "品红",
        "hsl_hue": "色相",
        "hsl_sat": "饱和",
        "hsl_lum": "明度",
        "thumb_size_lbl": "缩略图",
        "thumb_small": "小",
        "thumb_medium": "中",
        "thumb_large": "大",
        "filter_lbl": "筛选",
        "auto_levels": "自动色阶（直方图拉伸）",
        "srgb": "转 sRGB 色彩空间",
        "flatten_cmyk": "CMYK 转 RGB",
        "evaluate": "计算 SSIM 质量评分",
        "blur_score": "计算模糊评分",
        "resume": "断点续传（跳过已处理文件）",
        "print_size": "打印尺寸",
        "print_size_hint": "如 8x10@300dpi；空 = 不裁剪",
        # Metadata
        "sec_metadata": "元数据",
        "date_shift": "EXIF 日期偏移",
        "date_shift_hint": "如 -5h30m；空 = 不改",
        "sync_date": "输出时间 ← EXIF 拍摄时间",
        "scrub": "清除全部元数据 (EXIF+ICC+GPS)",
        "gpx_trace": "GPX 轨迹文件",
        "gpx_trace_hint": "按拍摄时间插值写入 GPS；空 = 不写入",
        "browse_gpx": "浏览…",
        "blur_faces": "人脸模糊",
        "blur_faces_off": "关闭",
        "blur_faces_blur": "模糊",
        "blur_faces_pixelate": "马赛克",
        "blur_faces_margin_lbl": "外扩 %",
        "blur_faces_hint": "检测并模糊人脸（需 pip install photo-s-tools[enhance]）",
        "cmp_no_result": "无对比结果",
        "cmp_no_result_body": "该文件尚未处理或处理失败。\nProcess this file first to compare before/after.",
        # About
        "about_title": "关于 PhotoS",
        "about_desc": "批量图片压缩与格式转换工具（命令行 + 图形界面）",
        "about_features": "功能特性",
        "about_feature_list": (
            "· 批量压缩 JPEG / PNG / WebP / TIFF / BMP / HEIC / AVIF\n"
            "· 支持相机 RAW 格式（需安装 rawpy）\n"
            "· 目标大小自动调优、缩放、智能重命名\n"
            "· 并行处理、EXIF 保留、子文件夹整理"
        ),
        "about_env": "运行环境",
        "about_deps": "可选组件",
        "dep_installed": "已安装",
        "dep_missing": "未安装",
        "about_license": "开源协议: MIT License",
        # ── More tools menu ──
        "more_btn": "更多工具",
        "more_watch": "目录监视",
        "more_contact": "联系表",
        "more_cull": "曝光筛选",
        "more_hash": "校验和",
        "more_hdr": "HDR 合并",
        "more_presets": "预设",
        # ── Visual preview ──
        "preview_render": "正在渲染预览…",
        "preview_error": "预览失败: {err}",
        "preview_rendered": "原始 {in_size} → 处理 {out_size} · 质量 {q}",
        # ── Folder watcher ──
        "watch_title": "目录监视",
        "watch_dir": "监视目录",
        "watch_recursive": "包含子文件夹",
        "watch_outdir": "输出目录（留空 = 原目录）",
        "watch_format": "输出格式",
        "watch_quality": "质量",
        "watch_remove_original": "处理后删除原文件",
        "watch_start": "开始监视",
        "watch_stop": "停止",
        "watch_running": "监视中…",
        "watch_stopped": "已停止",
        "watch_processed": "已处理 {n} 个文件",
        "watch_no_dir": "请选择要监视的目录",
        "watch_no_watchdog": "未安装 watchdog，请运行 pip install photo-s-tools[watch]",
        # ── Contact sheet ──
        "contact_title": "联系表",
        "contact_output": "输出文件",
        "contact_cols": "列数",
        "contact_thumb": "缩略图尺寸 WxH",
        "contact_caption": "显示文件名",
        "contact_bg": "背景色 (#RRGGBB)",
        "contact_generate": "生成",
        "contact_done": "已生成: {path}",
        "contact_failed": "生成失败: {err}",
        "contact_open": "打开",
        "contact_need_files": "请先添加并勾选图片",
        "contact_bad_bg": "背景色无效，已用黑色",
        # ── HDR merge ──
        "hdr_title": "HDR 合并",
        "hdr_need_files": "请勾选至少 2 张包围曝光图片",
        "hdr_count": "将合并 {n} 张曝光",
        "hdr_output": "输出文件",
        "hdr_align": "手持对齐（AlignMTB，消除鬼影）",
        "hdr_merge": "合并 HDR",
        "hdr_done": "已生成: {out}",
        "hdr_failed": "合并失败: {err}（需 pip install photo-s-tools[enhance]）",
        # ── Cull ──
        "cull_title": "曝光筛选",
        "cull_overexposed": "过曝上限 %",
        "cull_underexposed": "欠曝上限 %",
        "cull_lum_min": "亮度下限 (0-1)",
        "cull_lum_max": "亮度上限 (0-1)",
        "cull_sharp": "清晰度下限",
        "cull_scan": "扫描",
        "cull_apply": "仅保留符合的",
        "cull_kept": "符合 {kept}/{total}",
        "cull_failed": "扫描失败: {err}",
        "cull_no_files": "文件列表为空",
        "cull_processing": "处理中，无法应用筛选",
        "undo_cull": "撤销筛选（恢复 {n} 张）",
        # ── Checksums ──
        "hash_title": "校验和",
        "hash_tab_gen": "生成清单",
        "hash_tab_verify": "校验",
        "hash_output": "输出文件",
        "hash_generate": "生成",
        "hash_done": "已写入 {path}（{n} 项）",
        "hash_failed": "失败: {err}",
        "hash_choose": "选择清单",
        "hash_verify": "校验",
        "hash_total": "共 {n} 项",
        "hash_ok": "一致 {n}",
        "hash_missing": "缺失 {n}",
        "hash_mismatched": "不匹配 {n}",
        "hash_all_ok": "全部一致",
        "hash_open": "打开",
        "hash_no_files": "没有要哈希的文件",
        # ── Batch rename ──
        "rename_btn": "重命名",
        "rename_title": "批量重命名",
        "rename_pattern_lbl": "命名模板",
        "rename_mode_inplace": "就地重命名",
        "rename_mode_copy": "复制到目录",
        "rename_overwrite": "覆盖同名文件",
        "rename_col_old": "原文件名",
        "rename_col_new": "新文件名",
        "rename_col_status": "状态",
        "rename_status_conflict": "冲突·自动加后缀",
        "rename_conflict_note": "批内重名，实际将保存为 {name}",
        "rename_counts": "{n} 个文件 · {c} 个冲突 · {e} 个错误",
        "rename_preview_updating": "预览更新中…",
        "rename_need_dir": "请先选择输出目录",
        "rename_execute": "执行重命名",
        "rename_confirm": "将按预览重命名 {n} 个文件，此操作不可撤销。继续？",
        "rename_done": "完成：{ok} 个成功（{c} 个自动加后缀）· {e} 个失败",
        # ── Presets ──
        "presets_title": "预设",
        "presets_list": "预设列表",
        "presets_name": "名称",
        "presets_desc": "描述",
        "presets_save": "保存当前设置",
        "presets_load": "加载",
        "presets_delete": "删除",
        "presets_saved": "已保存",
        "presets_loaded": "已加载: {name}",
        "presets_deleted": "已删除: {name}",
        "presets_name_required": "请输入预设名称",
        "presets_load_failed": "加载失败: {name}",
        "presets_empty": "（空）",
        "presets_confirm_delete": "删除预设 {name}？",
        # ── Multi-image compare ──
        "compare_btn": "对比",
        "compare_view_title": "多图对比",
        "compare_need_two": "请勾选至少 2 张图片进行对比（最多显示前 4 张）",
        "compare_hint": "滚轮缩放 · 左键拖拽平移（均仅当前图）· 双击全部复位",
        "compare_sync_zoom": "同步缩放",
        "compare_loading": "加载中…",
        # ── v2.0 workspace modules ──
        "module_library": "图库",
        "module_develop": "修图",
        "module_export": "导出",
        "module_tools": "工具",
        "dev_hint": "在胶片条选择照片 · 设置改动自动经真实管线重渲染（约 0.5s 防抖）",
        "dev_no_selection": "未选择照片 — 在「图库」添加并勾选后自动出现",
        "dev_rendering": "渲染中…",
        "dev_render_failed": "渲染失败: {err}",
        "dev_hist_title": "直方图（处理后）",
        "dev_exposure_line": "亮度 {lum} · 过曝 {over}% · 欠曝 {under}% · 清晰度 {blur}",
        "dev_kelvin_line": "色温估计 {k}K · G-M {tint}",
        "dev_show_before": "显示原图",
        "dev_show_after": "显示效果",
        "tools_open": "打开",
        "tools_desc_review": "灯箱浏览 · 0–5 打分 · 关键词/标题标注 · 按评分一键分拣",
        "tools_desc_dedup": "感知哈希找出重复组，最锐的一张预勾选，其余移入回收目录",
        "tools_desc_compare": "多图并排对比 · 滚轮缩放 · 同步缩放开关",
        "tools_desc_gallery": "导出自包含 HTML 画廊（缩略图 + 网格）",
        "tools_desc_contact": "把勾选的照片拼成联系表大图",
        "tools_desc_cull": "按曝光/清晰度阈值批量筛选；评分排序 + 连拍组留最佳",
        "tools_desc_hash": "生成 SHA-256 校验清单，或校验已有清单完整性",
        "tools_desc_hdr": "包围曝光合并（手持对齐），输出 HDR 融合图",
        "tools_desc_watch": "监视目录，新文件自动按当前设置处理",
        "tools_desc_rename": "按日期/相机/序号模板批量重命名，实时预览",
        "tools_desc_presets": "保存当前设置为命名预设，或一键套用",
        "tools_desc_analyze": "当前选中照片的曝光/清晰度/色温分析",
        # ── Export queue ──
        "export_queue": "导出队列",
        "export_queue_hint": "以下勾选的照片将按右侧设置导出（在「图库」页勾选/取消）",
        "export_queue_empty": "尚未勾选照片 — 在「图库」页勾选后再来导出",
        # ── v2.2 editing efficiency ──
        "dev_copy_settings": "复制设置",
        "dev_paste_settings": "粘贴设置",
        "dev_undo": "撤销",
        "dev_redo": "重做",
        "settings_copied": "已复制当前照片的调整设置",
        "paste_need_copy": "请先「复制设置」",
        "paste_need_checked": "请先在「图库」页勾选照片",
        "paste_done": "已粘贴到 {n} 张照片",
        "paste_to_checked": "粘贴设置到勾选照片",
        "export_adjusted_badge": "已调",
        "export_adjusted_count": "{n} 张已单独调整",
        "export_recipes": "导出配方",
        "recipe_apply": "套用",
        "recipe_save": "存为配方",
        "recipe_delete": "删除",
        "recipe_need_name": "请先输入配方名称",
        "recipe_need_pick": "请先选择一个配方",
        "recipe_saved": "配方已保存：{name}",
        "recipe_applied": "已套用配方：{name}",
        "recipe_deleted": "配方已删除：{name}",
    },
    "en": {
        "window_title": "PhotoS — Batch Image Compression & Conversion",
        "subtitle": "Batch Image Compression & Conversion",
        "about": "About",
        "theme_toggle": "Toggle dark/light mode",
        # Toolbar / file list
        "add_images": "Add Images",
        "add_folder": "Add Folder",
        "remove": "Remove",
        "clear": "Clear All",
        "files_count": "{n} files",
        "files_count_checked": "{n} files · {m} checked",
        "check_none": "Check the images to process first (use the checkboxes, or the check-all button)",
        "check_toggle_all": "Check all / none",
        "undo": "Undo",
        "undo_none": "Nothing to undo",
        "undo_failed": "Undo failed: {err}",
        "redo": "Redo",
        "redo_none": "Nothing to redo",
        "undo_removed": "Undo removal of {n}",
        "undo_dedup": "Undo dedup move of {n}",
        "undo_tag": "Undo tagging: {name}",
        "undo_done": "Undone",
        "about_shortcuts": "Shortcuts 快捷键",
        "shortcuts_text": "⌘O / Ctrl+O Add images\n⌘⇧O / Ctrl+Shift+O Add folder\n⌘R / Ctrl+R Start processing (Esc cancels)\n⌘P / Ctrl+P Preview options\n⌘E / Ctrl+E Review & rate\n⌘D / Ctrl+D Duplicates\n⌘G / Ctrl+G Export gallery\n⌘Z / Ctrl+Z Undo\n(In review: ←/→ navigate, 0-5 rate, ⌘Z undo, Esc close)",
        "dlg_skipped": "Imported {n} images, skipped {m} unsupported files",
        "dlg_no_supported": "No supported images found (skipped {m} unsupported files)",
        "hint_dnd": "Drag & drop images/folders into the list, or use the buttons above",
        "hint_no_dnd": "Use the buttons above to add images (install tkinterdnd2 for drag & drop)",
        "col_name": "Name",
        "col_size": "Size",
        "col_format": "Format",
        "col_dims": "Dimensions",
        # Settings sections
        "sec_format": "Output Format",
        "sec_mode": "Compression Mode",
        "manual_quality": "Manual Quality",
        "target_size_mode": "Target Size",
        "quality": "Quality",
        "max_quality": "Max Quality",
        "target_size": "Target Size",
        "autotune_hint": "auto-tune quality",
        "sec_resize": "Resize",
        "width": "W",
        "height": "H",
        "pixels_hint": "pixels, blank = no resize",
        "scale": "Scale %",
        "sec_output": "Output Location",
        "browse": "Browse…",
        "sec_naming": "Naming",
        "prefix": "Prefix",
        "suffix": "Suffix",
        "smart_rename": "Smart Rename",
        "rename_vars": "vars: {date} {camera} {original} {seq} {iso} {focal}",
        "sec_subfolder": "Subfolder",
        "template": "Template",
        "preset_flat": "Flat (no grouping)",
        "preset_date": "By date",
        "preset_camera": "By camera",
        "preset_date_camera": "By date+camera",
        "preset_custom": "Custom…",
        "custom": "Custom",
        "folder_vars": "blank = flat. vars: {year} {month} {day} {date} {camera} {make}",
        "sec_options": "Options",
        "preserve_exif": "Preserve EXIF",
        "optimize": "Optimize",
        "progressive": "Progressive JPEG",
        "jpeg_subsampling": "JPEG chroma subsampling (444 = full color)",
        "overwrite": "Overwrite existing files",
        "auto_rotate": "Auto-rotate (EXIF Orientation)",
        "raw_half_size": "RAW half-size decode (faster)",
        "raw_demosaic": "RAW demosaic algorithm",
        "raw_color_space": "RAW color space",
        "raw_16bit": "16-bit RAW decode (TIFF output)",
        "raw_auto_bright": "RAW auto brightness",
        "delete_original": "Delete original after processing",
        "strip_gps": "Strip GPS data",
        "keep_mtime": "Keep file mtime",
        "max_pixels": "Max pixels (longest side)",
        "max_pixels_hint": "pixels, blank = no limit, downscale only",
        "jobs": "Parallel jobs",
        # Cutout / background removal (v2.1.0)
        "sec_cutout": "Cutout (background removal)",
        "cutout_mode": "Mode",
        "cutout_off": "Off",
        "cutout_subject": "Subject (AI)",
        "cutout_person": "Person (AI)",
        "cutout_object": "Object (AI)",
        "cutout_color": "Color key",
        "cutout_label": "COCO class",
        "cutout_r": "R",
        "cutout_g": "G",
        "cutout_b": "B",
        "cutout_tol": "Tolerance",
        "cutout_feather": "Feather",
        "cutout_hint": "Transparency needs PNG/WebP/TIFF/AVIF/HEIC; JPEG errors per file",
        "cutout_ai_hint": "AI segmentation needs photo-s-tools[enhance]; weights auto-download on first use",
        # Bottom bar
        "ready": "Ready — add images to begin",
        "preview": "Preview",
        "start": "Start",
        "cancel": "Cancel",
        "cancelling": "Cancelling…",
        "processing": "Processing…",
        "processing_item": "Processing [{cur}/{total}] {name}",
        "tuning": "Tuning quality…",
        "cancelled_status": "Cancelled — {ok} done, {fail} failed/skipped",
        "done_status": "Done — {ok}/{total} succeeded, saved {savings} ({pct}%)",
        "failed_status": "Processing failed",
        "stats_result": "Original: {sin} → Compressed: {sout}  |  Saved {pct}%",
        "stats_files": "{n} files selected  |  Total: {size}",
        "stats_files_only": "{n} files selected",
        # Dialogs
        "dlg_no_files_title": "No Files",
        "dlg_no_files": "Please add images first.",
        "dlg_confirm_clear_title": "Confirm Clear",
        "dlg_confirm_clear": "Clear all {n} files from the list?",
        "dlg_added_title": "Already Added",
        "dlg_added": "All {n} images from the folder are already in the list.",
        "dlg_no_images_title": "No Images",
        "dlg_no_images": "No supported image files found in this folder.",
        "dlg_drop_none": "No addable image files found in the dropped content.",
        "dlg_confirm_delete_title": "Confirm Delete",
        "dlg_confirm_delete": "{n} original file(s) will be deleted after processing!\n\nAre you sure?",
        "dlg_error_title": "Processing Error",
        "dlg_error": "An error occurred during batch processing:\n\n{err}",
        # Preview
        "preview_title": "Preview",
        "preview_header": "Preview — no files will be modified",
        "pv_files": "Files: {n}",
        "pv_format": "Format: {fmt}",
        "pv_target": "Target size: {size} (auto-tune)",
        "pv_qmax": "Quality max: {q}",
        "pv_quality": "Quality: {q}",
        "pv_maxsize": "Max size: {w}×{h}",
        "pv_scale": "Scale: {s}%",
        "pv_exif": "Preserve EXIF: {yn}",
        "pv_optimize": "Optimize: {yn}",
        "pv_progressive": "Progressive: {yn}",
        "pv_overwrite": "Overwrite: {yn}",
        "pv_outdir": "Output dir: {d}",
        "pv_outdir_same": "(same as source)",
        "pv_subfolder": "Subfolder: {p}",
        "pv_prefix": "Prefix: '{p}'",
        "pv_suffix": "Suffix: '{s}'",
        "pv_total": "Total source size: {size}",
        "yes": "Yes",
        "no": "No",
        "auto": "auto",
        # Summary / comparison
        "summary_title": "Complete",
        "sum_header": "Processing Complete",
        "sum_success": "Successful",
        "sum_failed": "Failed",
        "sum_original": "Original",
        "sum_compressed": "Compressed",
        "sum_saved": "Saved",
        "sum_ask_compare": "Show before/after comparison?",
        "sum_view_compare": "View comparison",
        "compare_title": "Comparison",
        "compare_header": "Before & After",
        "before": "Original",
        "after": "Compressed",
        "saved": "Saved",
        "quality_lbl": "Quality",
        "cannot_load": "Cannot load",
        "close": "Close",
        # Plugins
        "plugins": "Plugins",
        "plugins_title": "Plugin Manager",
        "plugins_installed": "Installed plugins",
        "plugins_available": "Available official plugins",
        "plugins_none": "(none)",
        "plugins_install": "Install",
        "plugins_uninstall": "Uninstall",
        "plugins_fetch": "Fetch weights",
        "plugins_refresh": "Refresh",
        "plugins_ok": "✅ {what}",
        "plugins_err": "❌ {detail}",
        # Exposure analysis
        "analyze": "Exposure analysis",
        "review_btn": "Review & Rate",
        "dedup_btn": "Duplicates",
        "gallery_btn": "Gallery",
        "gallery_title": "Export Gallery",
        "gallery_name": "Gallery title",
        "gallery_thumb": "Thumbnail size",
        "gallery_out": "Output directory",
        "gallery_generate": "Generate",
        "gallery_generating": "Generating…",
        "gallery_done": "Generated {count} images → {path}",
        "gallery_open": "Open in browser",
        "gallery_need_files": "Add images first",
        "gallery_need_dir": "Choose an output directory",
        "gallery_error": "Failed: {err}",
        "op_failed": "Operation failed: {err}",
        "dedup_title": "Duplicate Viewer",
        "dedup_scanning": "Scanning… {n}/{total}",
        "dedup_none": "No duplicates found",
        "dedup_group": "Group {i}",
        "dedup_keep": "Keep",
        "dedup_sharpest": "★sharpest",
        "dedup_blur": "blur",
        "dedup_execute": "Move unchecked to trash",
        "dedup_moving": "Moving…",
        "dedup_moved": "Moved {n} images to {dir}",
        "dedup_rescan": "Rescan",
        "dedup_confirm": "Move {n} images to a trash subfolder (nothing is deleted). Continue?",
        "dedup_none_selected": "Nothing to clean up (every group must keep at least one image)",
        "review_title": "Review & Rate",
        "review_pos": "{i} / {n}",
        "review_loading": "Reading metadata… {n}/{total}",
        "review_rating": "Rating",
        "review_keywords": "Keywords",
        "review_title_lbl": "Title",
        "review_save": "Save",
        "review_saved": "Saved",
        "review_save_failed": "Write failed: {err}",
        "review_filter": "Filter",
        "review_min_rating": "Min rating",
        "review_filter_kw": "Keyword contains",
        "review_apply_filter": "Apply",
        "review_clear_filter": "Clear",
        "review_empty": "No matching images",
        "review_no_piexif": "⚠️ piexif not installed: view only (pip install photo-s-tools[exif])",
        "review_prev": "◀ Prev",
        "review_next": "Next ▶",
        "review_none": "Add images first",
        "review_shooting": "Shooting info",
        "review_make": "Make",
        "review_model": "Model",
        "review_lens": "Lens",
        "review_iso": "ISO",
        "review_shutter": "Shutter (e.g. 1/250)",
        "review_aperture": "Aperture (e.g. 2.8)",
        "review_date": "Date (YYYY:MM:DD HH:MM:SS)",
        "review_select_lbl": "Selects",
        "review_rejects_lbl": "Rejects",
        "review_select_go": "Move keepers/rejects",
        "review_select_browse": "Choose a target folder",
        "review_select_need_dir": "Set at least one target folder (selects or rejects)",
        "review_select_done": "Moved {n} files",
        "review_select_done_warn": "Moved {ok}, {err} failed",
        "analyze_title": "Exposure Stats",
        "analyze_none": "Select an image in the file list first",
        "analyze_err": "Cannot read that image",
        "analyze_luminance": "Mean luminance",
        "analyze_over": "Overexposed (≥250)",
        "analyze_under": "Underexposed (≤5)",
        "analyze_blur": "Blur score",
        "analyze_histogram": "Luminance histogram",
        # Settings dialog (MCP + optional deps)
        "settings": "Settings",
        "settings_title": "Settings",
        "set_mcp": "MCP Server",
        "set_mcp_desc": "Let MCP clients (Claude Desktop, agents) call PhotoS tools",
        "mcp_installed": "Installed",
        "mcp_missing": "Not installed",
        "mcp_install_hint": "Install: pip install 'photo-s-tools[mcp]'",
        "mcp_launch": "Launch command",
        "mcp_claude_config": "Claude Desktop config",
        "mcp_claude_snippet": (
            "{\n  \"mcpServers\": {\n    \"photo-s\": {\n"
            "      \"command\": \"photo-s\",\n      \"args\": [\"mcp\"]\n"
            "    }\n  }\n}"
        ),
        "copy": "Copy",
        "copied": "Copied",
        "set_deps": "Optional dependencies",
        "dep_install": "Install",
        "dep_installing": "Installing…",
        "set_plugins_link": "Open Plugin Manager",
        # Watermark
        "sec_watermark": "Watermark",
        "wm_text": "Text",
        "wm_image": "Image",
        "wm_position": "Position",
        "wm_opacity": "Opacity",
        # Multi-size
        "sec_sizes": "Multi-size",
        "sizes_hint": "format: label:WxH, e.g. thumb:480x,screen:1920x1080",
        # Adjust
        "sec_adjust": "Adjust",
        "brightness": "Brightness",
        "contrast": "Contrast",
        "saturation": "Saturation",
        "gamma": "Gamma",
        "sharpen": "Sharpen",
        "export_sharpen": "Export sharpen (0 off)",
        "highlight_recovery": "Highlight recovery (0 off)",
        "grayscale": "Grayscale",
        "sepia": "Sepia",
        # Composition
        "sec_composition": "Composition",
        "crop": "Crop",
        "crop_hint": "format: WxH+X+Y, e.g. 800x600+100+50",
        "crop_ratio": "Crop ratio",
        "rotate": "Rotate°",
        "rotate_bg": "Rotate fill",
        "flip": "Flip",
        "flip_hint": "h = horizontal, v = vertical",
        "pad": "Pad ratio",
        "pad_bg": "Pad bg",
        "pad_hint": "e.g. 16:9, 1:1 (blank = no padding)",
        # Correction (exposure / LOG / denoise / straighten)
        "sec_correction": "Correction",
        "ev": "Exposure (EV)",
        "ev_hint": "EV stops, 2^EV gain (0 = unchanged)",
        "auto_exposure": "Auto-exposure target (0-1)",
        "auto_exposure_hint": "Normalize mean luminance (blank = off)",
        "log_curve": "LOG recovery",
        "log_curve_hint": "SLOG3/CLOG3/LOGC3/DLOG/VLOG/HLG (blank = off)",
        "denoise": "Denoise strength (0-20)",
        "denoise_hint": "NLM denoise (blank = off; needs photo-s-tools[enhance] or SCUNet plugin)",
        "lut": "LUT grading (.cube)",
        "lut_hint": ".cube file or preset name (filmic-v1 etc. with "
                    "photo-s-plugin-lut; blank = off)",
        "auto_straighten": "Auto-straighten horizon",
        "max_straighten_angle": "Max straighten angle°",
        # White balance / color / evaluation
        "wb_temp": "White balance temp (K)",
        "wb_temp_hint": "e.g. 5600; blank = off",
        "wb_reference": "WB reference image",
        "wb_reference_hint": "gray-card path; blank = no sampling",
        "browse_ref": "Browse…",
        # Lightroom-direction grading (v1.6.0)
        "sec_grading": "Grading (LR-direction)",
        "wb_tint": "WB tint (green-/magenta+)",
        "wb_tint_hint": "-100~100; blank = off",
        "levels": "Manual levels",
        "levels_hint": "black,white[,gamma] e.g. 80,200,1.1; blank = off",
        "curves": "Point curves",
        "curves_hint": "per-channel points ch:x,y;x,y e.g. 0,0;128,140;255,255; blank = off",
        "vibrance": "Vibrance",
        "vibrance_hint": "-1~1; blank = off",
        "color_grading": "3-way color grading",
        "color_grading_hint": "zone:hue,sat e.g. shadows:120,0.3; blank = off",
        "hsl": "HSL split",
        "hsl_hint": "color:h,s,l e.g. green:10,0.2,0.1; blank = off",
        "clarity": "Clarity",
        "clarity_hint": "-1~1; blank = off",
        "texture": "Texture",
        "texture_hint": "-1~1; blank = off",
        "dehaze": "Dehaze",
        "dehaze_hint": "-1~1 (negative adds haze); blank = off",
        "vignette": "Vignette",
        "vignette_hint": "amount[,mid[,feather]]; blank = off",
        "grain": "Grain",
        "grain_hint": "amount[,size]; blank = off",
        # Local adjustments + lens correction (v1.7.0)
        "point_color": "Point color",
        "point_color_hint": "Sampled-color targeting r,g,b:h,s,l[,range]; blank = off",
        "edit_point_color": "Point color…",
        "masks": "Local masks",
        "masks_hint": "Linear/radial/color-range masks + local adjustments; blank = off",
        "edit_masks": "Masks…",
        "sec_lens": "Lens correction",
        "lens_distort": "Distortion k1",
        "lens_distort_hint": "+ fixes barrel, - pincushion; blank = off",
        "lens_vignette": "Vignette fix",
        "lens_vignette_hint": "amount[,midpoint]; blank = off",
        "lens_ca": "CA fix",
        "lens_ca_hint": "r_scale,b_scale e.g. 0.999,1.001; blank = off",
        "lens_profile": "Lens profile (maintained via lens-profile save)",
        "dlt_point_color": "Point color (sample + range)",
        "dlt_masks": "Local mask editor",
        "pc_add": "Add",
        "pc_update": "Update",
        "pc_delete": "Delete",
        "pc_sample": "Sample color (R,G,B)",
        "pc_hue": "Hue shift",
        "pc_sat": "Saturation",
        "pc_lum": "Luminance",
        "pc_range": "Range tolerance",
        "mask_name": "Name",
        "mask_type": "Type",
        "mask_linear": "Linear gradient",
        "mask_radial": "Radial ellipse",
        "mask_color": "Color range",
        "mask_brush": "Brush",
        "mask_brush_size": "Brush radius (rel. short side)",
        "mask_brush_clear": "Clear strokes",
        "mask_workflow": "Canvas masks (LR-style)",
        "mask_prev": "◀ Prev",
        "mask_next": "Next ▶",
        "mask_page": "{cur}/{total}",
        "mask_add": "New mask",
        "mask_list": "Masks",
        "mask_show": "Show",
        "mask_hide": "Hide",
        "mask_del": "Delete mask",
        "mask_undo": "Undo (⌘Z)",
        "mask_mode_add": "A Add",
        "mask_mode_subtract": "B Subtract",
        "mask_mode_off": "◦ New",
        "mask_up": "▲ Up",
        "mask_down": "▼ Down",
        "mask_drag_hint": "Drag empty area = paint; drag inside a mask = move it",
        "mask_ai_empty": "AI found nothing (empty mask)",
        "mask_ai_overlay_warn":
            "AI mask cannot render (opencv missing or weights not "
            "downloaded): AI masks won't show on the canvas and that "
            "photo will fail in batch. Install photo-s-tools[enhance] "
            "or check with photo-s info.",
        "mask_bad_segment_warn":
            "Some mask segments could not be parsed: the broken ones were "
            "dropped and the rest kept (previously the whole list was "
            "silently cleared).",
        "preview_per_photo_hint":
            "Note: preview excludes per-photo masks (injected at batch)",
        "mask_tool": "Tool",
        "mask_tool_linear": "Linear gradient",
        "mask_tool_radial": "Radial ellipse",
        "mask_tool_brush": "Brush",
        "mask_tool_color": "Color pick",
        "mask_tool_subject": "AI subject",
        "mask_tool_person": "AI person",
        "mask_tool_object": "AI object",
        "mask_ai_label": "Object class (COCO)",
        "mask_overlay_hint": "Drag on the canvas to paint; colored translucent areas = mask active (all visible masks overlaid)",
        "mask_apply_all": "Apply to all checked photos",
        "mask_empty_hint": "Check photos, then paint masks on the canvas",
        "mask_no_check": "Check the photos you want to edit first",
        "mask_feather": "Feather",
        "mask_invert": "Invert",
        "mask_params": "Params",
        "mask_adjust_sec": "Adjustments inside mask (sliders, 0 = untouched)",
        "adj_exposure": "Exposure EV",
        "adj_brightness": "Brightness",
        "adj_contrast": "Contrast",
        "adj_saturation": "Saturation",
        "adj_vibrance": "Vibrance",
        "adj_clarity": "Clarity",
        "adj_texture": "Texture",
        "adj_sharpen": "Sharpen",
        "adj_temp": "Temp K",
        "adj_tint": "Tint G-/M+",
        "adj_blur": "Blur radius px",
        "mask_preview": "Mask preview",
        "mask_refresh": "Refresh preview",
        "mask_no_preview": "Check a file to preview",
        # settings category tabs (v1.6.1)
        "tab_output": "Output",
        "tab_adjust": "Adjust",
        "tab_fx": "Effects",
        "tab_metadata": "Metadata",
        "tab_options": "Options",
        # interactive editors (v1.6.x)
        "edit_curves": "Edit curves…",
        "edit_wheels": "Color wheels…",
        "edit_hsl": "HSL…",
        "dlt_curves": "Curve editor (drag points, double-click to add, right-click to remove)",
        "dlt_wheels": "Color grading (click / drag to pick)",
        "dlt_hsl": "HSL split (pick a chip, then drag the sliders)",
        "ok": "OK",
        "grade_none": "not set",
        "grade_lum": "Lum",
        "reset": "Reset",
        "zone_shadows": "Shadows",
        "zone_midtones": "Midtones",
        "zone_highlights": "Highlights",
        "hsl_red": "Red",
        "hsl_orange": "Orange",
        "hsl_yellow": "Yellow",
        "hsl_green": "Green",
        "hsl_aqua": "Aqua",
        "hsl_blue": "Blue",
        "hsl_purple": "Purple",
        "hsl_magenta": "Magenta",
        "hsl_hue": "Hue",
        "hsl_sat": "Sat",
        "hsl_lum": "Lum",
        "thumb_size_lbl": "Thumb",
        "thumb_small": "S",
        "thumb_medium": "M",
        "thumb_large": "L",
        "filter_lbl": "Filter",
        "auto_levels": "Auto levels (histogram stretch)",
        "srgb": "Convert to sRGB",
        "flatten_cmyk": "Flatten CMYK → RGB",
        "evaluate": "Compute SSIM score",
        "blur_score": "Compute blur score",
        "resume": "Resume (skip already-processed files)",
        "print_size": "Print size",
        "print_size_hint": "e.g. 8x10@300dpi; blank = no crop",
        # Metadata
        "sec_metadata": "Metadata",
        "date_shift": "EXIF date shift",
        "date_shift_hint": "e.g. -5h30m; blank = off",
        "sync_date": "Output mtime ← EXIF datetime",
        "scrub": "Strip ALL metadata (EXIF+ICC+GPS)",
        "gpx_trace": "GPX track file",
        "gpx_trace_hint": "interpolate GPS from timestamps; blank = off",
        "browse_gpx": "Browse…",
        "blur_faces": "Face blur",
        "blur_faces_off": "Off",
        "blur_faces_blur": "Blur",
        "blur_faces_pixelate": "Mosaic",
        "blur_faces_margin_lbl": "margin %",
        "blur_faces_hint": "Detect & blur faces (needs pip install photo-s-tools[enhance])",
        "cmp_no_result": "No comparison",
        "cmp_no_result_body": "This file was not processed yet (or failed).\nProcess it first to compare before/after.",
        # About
        "about_title": "About PhotoS",
        "about_desc": "Batch image compression & format conversion tool (CLI + GUI)",
        "about_features": "Features",
        "about_feature_list": (
            "· Batch compress JPEG / PNG / WebP / TIFF / BMP / HEIC / AVIF\n"
            "· Camera RAW support (requires rawpy)\n"
            "· Target-size auto-tuning, resizing, smart renaming\n"
            "· Parallel processing, EXIF preservation, subfolder organization"
        ),
        "about_env": "Environment",
        "about_deps": "Optional Components",
        "dep_installed": "installed",
        "dep_missing": "not installed",
        "about_license": "License: MIT License",
        # ── More tools menu ──
        "more_btn": "More Tools",
        "more_watch": "Folder Watcher",
        "more_contact": "Contact Sheet",
        "more_cull": "Cull Filter",
        "more_hash": "Checksums",
        "more_hdr": "HDR Merge",
        "more_presets": "Presets",
        # ── Visual preview ──
        "preview_render": "Rendering preview…",
        "preview_error": "Preview failed: {err}",
        "preview_rendered": "{in_size} → {out_size} · q{q}",
        # ── Folder watcher ──
        "watch_title": "Folder Watcher",
        "watch_dir": "Watch directory",
        "watch_recursive": "Include subfolders",
        "watch_outdir": "Output dir (blank = same folder)",
        "watch_format": "Output format",
        "watch_quality": "Quality",
        "watch_remove_original": "Delete original after processing",
        "watch_start": "Start watching",
        "watch_stop": "Stop",
        "watch_running": "Watching…",
        "watch_stopped": "Stopped",
        "watch_processed": "Processed {n} files",
        "watch_no_dir": "Pick a directory to watch",
        "watch_no_watchdog": "watchdog not installed — pip install photo-s-tools[watch]",
        # ── Contact sheet ──
        "contact_title": "Contact Sheet",
        "contact_output": "Output file",
        "contact_cols": "Columns",
        "contact_thumb": "Thumbnail WxH",
        "contact_caption": "Show filenames",
        "contact_bg": "Background (#RRGGBB)",
        "contact_generate": "Generate",
        "contact_done": "Saved: {path}",
        "contact_failed": "Generation failed: {err}",
        "contact_open": "Open",
        "contact_need_files": "Add and check images first",
        "contact_bad_bg": "Invalid background color, using black",
        # ── HDR merge ──
        "hdr_title": "HDR Merge",
        "hdr_need_files": "Check at least 2 bracketed exposures",
        "hdr_count": "Merging {n} exposures",
        "hdr_output": "Output file",
        "hdr_align": "Align handheld (AlignMTB, kills ghosting)",
        "hdr_merge": "Merge HDR",
        "hdr_done": "Saved: {out}",
        "hdr_failed": "Merge failed: {err} (needs pip install photo-s-tools[enhance])",
        # ── Cull ──
        "cull_title": "Cull Filter",
        "cull_overexposed": "Overexposed max %",
        "cull_underexposed": "Underexposed max %",
        "cull_lum_min": "Luminance min (0-1)",
        "cull_lum_max": "Luminance max (0-1)",
        "cull_sharp": "Sharpness min",
        "cull_scan": "Scan",
        "cull_apply": "Keep only matches",
        "cull_kept": "Matched {kept}/{total}",
        "cull_failed": "Scan failed: {err}",
        "cull_no_files": "No files in the list",
        "cull_processing": "Cannot apply while processing",
        "undo_cull": "Undo cull (restore {n})",
        # ── Checksums ──
        "hash_title": "Checksums",
        "hash_tab_gen": "Generate",
        "hash_tab_verify": "Verify",
        "hash_output": "Output file",
        "hash_generate": "Generate",
        "hash_done": "Written {path} ({n} entries)",
        "hash_failed": "Failed: {err}",
        "hash_choose": "Choose manifest",
        "hash_verify": "Verify",
        "hash_total": "{n} entries",
        "hash_ok": "OK {n}",
        "hash_missing": "Missing {n}",
        "hash_mismatched": "Mismatched {n}",
        "hash_all_ok": "All OK",
        "hash_open": "Open",
        "hash_no_files": "Nothing to hash",
        # ── Batch rename ──
        "rename_btn": "Rename",
        "rename_title": "Batch Rename",
        "rename_pattern_lbl": "Name template",
        "rename_mode_inplace": "Rename in place",
        "rename_mode_copy": "Copy to folder",
        "rename_overwrite": "Overwrite existing files",
        "rename_col_old": "Original",
        "rename_col_new": "New name",
        "rename_col_status": "Status",
        "rename_status_conflict": "Conflict · auto-suffix",
        "rename_conflict_note": "Duplicate name in batch; will be saved as {name}",
        "rename_counts": "{n} files · {c} conflicts · {e} errors",
        "rename_preview_updating": "Updating preview…",
        "rename_need_dir": "Choose an output folder first",
        "rename_execute": "Rename files",
        "rename_confirm": "Rename {n} files as previewed? This cannot be undone.",
        "rename_done": "Done: {ok} renamed ({c} auto-suffixed) · {e} failed",
        # ── Presets ──
        "presets_title": "Presets",
        "presets_list": "Presets",
        "presets_name": "Name",
        "presets_desc": "Description",
        "presets_save": "Save current settings",
        "presets_load": "Load",
        "presets_delete": "Delete",
        "presets_saved": "Saved",
        "presets_loaded": "Loaded: {name}",
        "presets_deleted": "Deleted: {name}",
        "presets_name_required": "Enter a preset name",
        "presets_load_failed": "Failed to load: {name}",
        "presets_empty": "(empty)",
        "presets_confirm_delete": "Delete preset {name}?",
        # ── Multi-image compare ──
        "compare_btn": "Compare",
        "compare_view_title": "Compare Images",
        "compare_need_two": "Check at least 2 images to compare (up to 4 shown)",
        "compare_hint": "Wheel to zoom · drag to pan (both apply to the image under the cursor) · double-click resets all",
        "compare_sync_zoom": "Sync zoom",
        "compare_loading": "Loading…",
        # ── v2.0 workspace modules ──
        "module_library": "Library",
        "module_develop": "Develop",
        "module_export": "Export",
        "module_tools": "Tools",
        "dev_hint": "Pick a photo on the filmstrip · edits re-render through the real pipeline (~0.5s debounce)",
        "dev_no_selection": "No photo selected — add & check files in Library first",
        "dev_rendering": "Rendering…",
        "dev_render_failed": "Render failed: {err}",
        "dev_hist_title": "Histogram (processed)",
        "dev_exposure_line": "Luma {lum} · over {over}% · under {under}% · sharpness {blur}",
        "dev_kelvin_line": "Kelvin est. {k}K · G-M {tint}",
        "dev_show_before": "Show original",
        "dev_show_after": "Show processed",
        "tools_open": "Open",
        "tools_desc_review": "Lightbox review · rate 0–5 · keywords & title · sort by rating",
        "tools_desc_dedup": "Perceptual-hash duplicate groups, sharpest pre-checked, rest to trash",
        "tools_desc_compare": "Side-by-side compare · wheel zoom · sync-zoom toggle",
        "tools_desc_gallery": "Export a self-contained HTML gallery (thumbnails + grid)",
        "tools_desc_contact": "Lay the checked photos out into a contact sheet",
        "tools_desc_cull": "Exposure/sharpness thresholds + score ranking + burst keep-best",
        "tools_desc_hash": "Build a SHA-256 manifest, or verify an existing one",
        "tools_desc_hdr": "Merge bracketed exposures (handheld align) into one fused image",
        "tools_desc_watch": "Watch a folder — new files are auto-processed with current settings",
        "tools_desc_rename": "Template rename by date/camera/sequence with live preview",
        "tools_desc_presets": "Save current settings as a named preset, or apply one",
        "tools_desc_analyze": "Exposure / sharpness / Kelvin analysis of the selected photo",
        # ── Export queue ──
        "export_queue": "Export Queue",
        "export_queue_hint": "The checked photos below will be exported with the settings on the right (check/uncheck in Library)",
        "export_queue_empty": "No photos checked — check files in Library first",
        # ── v2.2 editing efficiency ──
        "dev_copy_settings": "Copy Settings",
        "dev_paste_settings": "Paste Settings",
        "dev_undo": "Undo",
        "dev_redo": "Redo",
        "settings_copied": "Copied this photo's adjustments",
        "paste_need_copy": "Copy settings first",
        "paste_need_checked": "Check photos in Library first",
        "paste_done": "Pasted to {n} photo(s)",
        "paste_to_checked": "Paste settings to checked",
        "export_adjusted_badge": "Edited",
        "export_adjusted_count": "{n} edited individually",
        "export_recipes": "Export Recipes",
        "recipe_apply": "Apply",
        "recipe_save": "Save Recipe",
        "recipe_delete": "Delete",
        "recipe_need_name": "Type a recipe name first",
        "recipe_need_pick": "Pick a recipe first",
        "recipe_saved": "Recipe saved: {name}",
        "recipe_applied": "Recipe applied: {name}",
        "recipe_deleted": "Recipe deleted: {name}",
    },
}
